import { useEffect, useState } from 'react';
import { course, getModule, getExam, type Module, type Quiz } from './course-data';
import './styles.css';

type View = 'home' | 'courses' | 'course' | 'resources' | 'lesson' | 'exam';
function parseRoute(){ const path = window.location.pathname; const parts = path.split('/').filter(Boolean); if(parts[0]==='courses'&&parts[1]==='architecture-ia'&&parts[2]==='examen') return {view:'exam' as View}; if(parts[0]==='courses'&&parts[1]==='architecture-ia'&&parts[2]) return {view:'lesson' as View, moduleId:parts[2]}; if(path==='/courses/architecture-ia') return {view:'course' as View}; if(path==='/courses') return {view:'courses' as View}; if(path==='/resources') return {view:'resources' as View}; return {view:'home' as View}; }
function go(path:string){ window.history.pushState({},'',path); window.scrollTo(0,0); window.dispatchEvent(new PopStateEvent('popstate')); }
function Nav(){return <header className="nav"><div className="wrap navin"><button onClick={()=>go('/')} className="brand reset"><span className="mark">dkm</span><span>Learning Hub</span></button><nav className="links"><button onClick={()=>go('/courses')}>Cours</button><button onClick={()=>go('/resources')}>Ressources</button><button onClick={()=>go('/courses/architecture-ia')}>Architecture IA</button></nav></div></header>}
function ModuleLink({m}:{m:Module}){return <button className="module reset" onClick={()=>go(`/courses/architecture-ia/${m.id}`)}><span className="num">{String(m.number).padStart(2,'0')}</span><span><strong>{m.title}</strong><small>{m.tome} · {m.eyebrow} · {m.minutes} min</small></span><span className="pill">ouvrir</span></button>}

function Home(){return <><Nav/><main><section className="hero wrap"><div className="eyebrow">God first · build in public · IA concrète</div><h1 className="display h1">Apprends l’IA comme un builder, pas comme un spectateur.</h1><p className="lead">DKM Learning Hub transforme les concepts IA en parcours simples, interactifs et actionnables. Premier cours MVP : Architecture IA, du neurone à l’agent.</p><div className="actions"><button className="btn" onClick={()=>go('/courses/architecture-ia')}>Commencer le cours</button><button className="btn light" onClick={()=>go('/resources')}>Voir les ressources</button></div></section><section className="section wrap grid grid3"><div className="card"><div className="eyebrow">01 · Comprendre</div><h2>Des bases claires.</h2><p>IA, ML, DL, neurones, Transformers et LLM sans jargon inutile.</p></div><div className="card"><div className="eyebrow">02 · Manipuler</div><h2>Des interactions.</h2><p>Démos, cartes mentales, quiz et glossaire issus des HTML source.</p></div><div className="card dark"><div className="eyebrow">03 · Construire</div><h2>Vers les agents.</h2><p>RAG, fine-tuning, tool use, MCP et garde-fous reliés à des cas concrets.</p></div></section><section className="section wrap"><div className="card"><div className="eyebrow">Cours vedette</div><h2 className="display section-title">{course.title}</h2><p className="lead">{course.promise}</p><div className="tags"><span className="pill">{course.duration}</span><span className="pill">{course.level}</span><span className="pill">{course.exam.length} questions d’examen</span></div><button className="btn" onClick={()=>go('/courses/architecture-ia')}>Ouvrir la fiche cours</button></div></section></main><footer className="footer wrap">@dkmarfo · apprendre, documenter, construire.</footer></>}

function Courses(){return <main className="wrap section"><button className="brand reset" onClick={()=>go('/')}><span className="mark">dkm</span><span>Learning Hub</span></button><div className="hero"><div className="eyebrow">Bibliothèque MVP</div><h1 className="display h1">Un premier cours solide, pensé pour grandir.</h1><p className="lead">La V1 garde le contenu en fichiers versionnés dans le repo. Supabase viendra plus tard pour la progression, les examens et les profils.</p></div><div className="card"><div className="eyebrow">Cours disponible</div><h2 className="display section-title">{course.title}</h2><p>{course.promise}</p><button className="btn" onClick={()=>go('/courses/architecture-ia')}>Voir le parcours</button></div></main>}

function CourseDetail(){return <main className="wrap section"><button className="brand reset" onClick={()=>go('/')}><span className="mark">dkm</span><span>Learning Hub</span></button><section className="hero"><div className="eyebrow">Cours MVP · 3 tomes · examen final</div><h1 className="display h1">{course.title}</h1><p className="lead">{course.promise}</p><div className="tags"><span className="pill">{course.duration}</span><span className="pill">{course.level}</span><span className="pill">{course.exam.length} questions d’examen</span></div><div className="actions"><button className="btn" onClick={()=>go(`/courses/architecture-ia/${course.modules[0].id}`)}>Commencer le tome 1</button><button className="btn light" onClick={()=>go('/courses/architecture-ia/examen')}>Passer l’examen</button></div></section><section className="grid grid2"><div className="card dark"><div className="eyebrow">Résultat attendu</div><h2>Tu relies concepts, outils et décisions.</h2><p>Chaque module suit le principe DKM : concept → mental model → exemple → quiz → application concrète.</p></div><div className="card"><div className="eyebrow">Glossaire</div><h2>{course.glossary.length} notions clés</h2><div className="gloss">{course.glossary.map((g)=><div className="gloss-item" key={g.term}><dt>{g.term}{g.fr?<span className="gloss-fr"> · {g.fr}</span>:null}</dt><dd>{g.def}</dd></div>)}</div></div></section><section className="section"><div className="eyebrow">Modules</div><h2 className="display section-title">Le parcours</h2><div className="modules">{course.modules.map((m)=><ModuleLink key={m.id} m={m}/>)}</div></section></main>}

function QuizBlock({quiz}:{quiz:Quiz}){const [picked,setPicked]=useState<number|null>(null); const done=picked!==null; const right=picked===quiz.answer; return <section className="section"><div className="card quiz-card"><div className="eyebrow">Mini-quiz</div><h2 className="quiz-q">{quiz.question}</h2><div className="opts">{quiz.options.map((o,i)=>{const state=!done?'':i===quiz.answer?'correct':i===picked?'wrong':''; return <button key={i} className={`opt reset ${state}`} disabled={done} onClick={()=>setPicked(i)}>{o}</button>})}</div>{done&&<p className={`quiz-fb ${right?'good':'bad'}`}>{right?quiz.ok:quiz.no}</p>}{done&&<button className="btn light quiz-retry" onClick={()=>setPicked(null)}>Réessayer</button>}</div></section>}

function Lesson({moduleId}:{moduleId?:string}){const module=moduleId ? getModule(moduleId) : course.modules[0]; if(!module) return <CourseDetail/>; const next=course.modules.find((m)=>m.number===module.number+1); const isLast=!next; return <main className="wrap section sidebar-layout"><aside className="side card"><button className="brand reset" onClick={()=>go('/')}><span className="mark">dkm</span><span>Hub</span></button><p className="side-title">{course.title}</p><div className="modules mini">{course.modules.map((m)=><button key={m.id} className={`side-link reset ${m.id===module.id?'on':''}`} onClick={()=>go(`/courses/architecture-ia/${m.id}`)}><span className="num">{String(m.number).padStart(2,'0')}</span> {m.nav}</button>)}<button className="side-link reset exam" onClick={()=>go('/courses/architecture-ia/examen')}>✦ Examen final</button></div></aside><article className="lesson card"><div className="eyebrow">{module.tome} · {module.eyebrow}</div><h1 className="display">{module.title}</h1><div className="lesson-body" dangerouslySetInnerHTML={{__html:module.bodyHtml}}/>{module.quiz&&<QuizBlock quiz={module.quiz}/>}<div className="actions"><button className="btn light" onClick={()=>go('/courses/architecture-ia')}>Retour au parcours</button>{next&&<button className="btn" onClick={()=>go(`/courses/architecture-ia/${next.id}`)}>Module suivant →</button>}{isLast&&<button className="btn" onClick={()=>go('/courses/architecture-ia/examen')}>Passer l’examen →</button>}</div></article></main>}

function ExamFlow(){const questions=getExam(); const [i,setI]=useState(0); const [answers,setAnswers]=useState<Record<number,number>>({}); const [done,setDone]=useState(false); const q=questions[i]; const picked=answers[q.n]; const choose=(opt:number)=>setAnswers((a)=>({...a,[q.n]:opt})); const answeredCount=Object.keys(answers).length; const score=questions.filter((x)=>answers[x.n]===x.answer).length;
  if(done){return <main className="wrap section"><button className="brand reset" onClick={()=>go('/')}><span className="mark">dkm</span><span>Learning Hub</span></button><section className="hero"><div className="eyebrow">Examen final · résultat</div><h1 className="display h1">{score} / {questions.length}</h1><p className="lead">{score>=15?'Excellent — tu maîtrises l’architecture de l’IA, du neurone à l’agent.':score>=10?'Bonne base. Revois les modules liés aux questions ratées.':'À retravailler : reprends les tomes puis retente l’examen.'}</p><div className="actions"><button className="btn" onClick={()=>{setAnswers({});setI(0);setDone(false)}}>Recommencer</button><button className="btn light" onClick={()=>go('/courses/architecture-ia')}>Retour au cours</button></div></section><section className="section"><div className="eyebrow">Corrections</div><div className="exam-review">{questions.map((x)=>{const ok=answers[x.n]===x.answer; return <div className={`card review-item ${ok?'good':'bad'}`} key={x.n}><div className="review-head"><span className="pill">{x.tome}</span><span className={`tag ${ok?'good':'bad'}`}>{ok?'✓ juste':'✗ raté'}</span></div><p className="review-q"><strong>{x.n}. {x.question}</strong></p><p className="review-a">Bonne réponse : {x.options[x.answer]}</p>{!ok&&picked!=null&&<p className="review-yours">Ta réponse : {answers[x.n]!=null?x.options[answers[x.n]]:'—'}</p>}{x.explain&&<p className="review-exp">{x.explain}</p>}</div>})}</div></section></main>}
  return <main className="wrap section"><button className="brand reset" onClick={()=>go('/')}><span className="mark">dkm</span><span>Learning Hub</span></button><section className="hero exam-hero"><div className="eyebrow">Examen final · {x_label(q)}</div><div className="exam-progress"><div className="progress-track"><div className="progress-fill" style={{width:`${((i+1)/questions.length)*100}%`}}/></div><span className="exam-count">Question {i+1} / {questions.length} · {answeredCount} répondues</span></div><h1 className="display exam-q">{q.question}</h1><div className="opts">{q.options.map((o,oi)=><button key={oi} className={`opt reset ${picked===oi?'picked':''}`} onClick={()=>choose(oi)}>{o}</button>)}</div><div className="actions"><button className="btn light" disabled={i===0} onClick={()=>setI(i-1)}>← Précédent</button>{i<questions.length-1?<button className="btn" onClick={()=>setI(i+1)}>Suivant →</button>:<button className="btn" disabled={answeredCount<questions.length} onClick={()=>setDone(true)}>Voir mon résultat</button>}</div>{i===questions.length-1&&answeredCount<questions.length&&<p className="exam-hint">Réponds aux {questions.length-answeredCount} question(s) restante(s) pour terminer.</p>}</section></main>}
function x_label(q:{tome:string}){return q.tome}

export default function App(){const [route,setRoute]=useState(parseRoute()); useEffect(()=>{const on=()=>setRoute(parseRoute()); window.addEventListener('popstate',on); return()=>window.removeEventListener('popstate',on)},[]); if(route.view==='courses') return <Courses/>; if(route.view==='course') return <CourseDetail/>; if(route.view==='resources') return <Resources/>; if(route.view==='exam') return <ExamFlow/>; if(route.view==='lesson') return <Lesson moduleId={route.moduleId}/>; return <Home/>;}

function Resources(){const resources=['Glossaire IA','Cheat sheet RAG vs fine-tuning','Checklist garde-fous agents','Prompts d’apprentissage','Framework concept → workflow']; return <main className="wrap section"><button className="brand reset" onClick={()=>go('/')}><span className="mark">dkm</span><span>Learning Hub</span></button><section className="hero"><div className="eyebrow">Ressources</div><h1 className="display h1">Des supports pour passer de la connaissance à l’action.</h1><p className="lead">Placeholder MVP : cette zone recevra templates, prompts, frameworks et fiches pratiques.</p></section><div className="grid grid3">{resources.map((r,i)=><div className="card" key={r}><div className="num">{String(i+1).padStart(2,'0')}</div><h2>{r}</h2><p>À produire à partir du contenu source et des besoins communauté.</p></div>)}</div></main>}
