export type Module = { id: string; tome: string; number: number; title: string; eyebrow: string; lead: string; quiz?: string; demo?: string; minutes: number };
export const course = { slug: 'architecture-ia', title: 'Architecture IA : du neurone à l’agent', promise: 'Comprends l’IA moderne depuis les bases, puis relie chaque concept aux workflows, agents et décisions business.', level: 'Débutant → builder', duration: '3 tomes · 20 modules · examen final', examQuestions: 18, glossary: ['IA','ML','DL','Token','Embedding','Transformer','LLM','RAG','Fine-tuning','RLHF','Agent','Tool use','MCP','Prompt injection','HITL'], modules: [
{ id:'tome1-intro', tome:'Tome 1 · La fabrique', number:1, title:'Les trois mots qu’on confond tout le temps', eyebrow:'IA / ML / DL', lead:'Avant de parler d’architecture, on remet de l’ordre dans les poupées russes : IA, apprentissage automatique, apprentissage profond.', demo:'Cercles emboîtés IA / ML / DL', quiz:'Laquelle de ces phrases est correcte ?', minutes:8 },
{ id:'tome1-neurone', tome:'Tome 1 · La fabrique', number:2, title:'La brique de base : un seul neurone', eyebrow:'Neurone artificiel', lead:'Un réseau complet commence par une petite recette : entrées, poids, somme, activation.', demo:'Simulateur de neurone', quiz:'À quoi sert la fonction d’activation ?', minutes:10 },
{ id:'tome1-reseau', tome:'Tome 1 · La fabrique', number:3, title:'On empile les neurones : le réseau', eyebrow:'Couches profondes', lead:'Les couches transforment un signal simple en représentation utile pour reconnaître, traduire ou prédire.', demo:'Signal qui traverse le réseau', quiz:'Que signifie “profond” ?', minutes:9 },
{ id:'tome1-apprentissage', tome:'Tome 1 · La fabrique', number:4, title:'Régler des millions de poids tout seul', eyebrow:'Entraînement', lead:'Apprendre, c’est ajuster les poids à partir de l’erreur. Pas de magie : une boucle d’amélioration.', demo:'Descente de gradient', quiz:'Que se passe-t-il si le taux d’apprentissage est trop grand ?', minutes:11 },
{ id:'tome1-specialisees', tome:'Tome 1 · La fabrique', number:5, title:'Des formes pour chaque type de données', eyebrow:'CNN · RNN · LSTM', lead:'Certaines architectures sont pensées pour les images, d’autres pour les séquences ou la mémoire longue.', demo:'Cartes comparatives CNN/RNN/LSTM', quiz:'Quelle architecture est naturelle pour une image ?', minutes:10 },
{ id:'tome1-transformer', tome:'Tome 1 · La fabrique', number:6, title:'La révolution : l’attention', eyebrow:'Transformer', lead:'Le Transformer permet à chaque mot de regarder les autres mots utiles. C’est le socle des LLM modernes.', demo:'Carte d’attention', quiz:'Quelle est l’idée centrale du Transformer ?', minutes:12 },
{ id:'tome1-llm', tome:'Tome 1 · La fabrique', number:7, title:'Tout ça pour deviner le mot suivant', eyebrow:'LLM', lead:'Un très gros Transformer entraîné sur beaucoup de texte apprend à prédire la suite, token par token.', demo:'Découpage en tokens', quiz:'Quelle est la tâche d’entraînement d’un LLM ?', minutes:10 },
{ id:'tome2-contexte', tome:'Tome 2 · L’adaptation', number:8, title:'La mémoire de travail du modèle', eyebrow:'Fenêtre de contexte', lead:'À chaque réponse, on redonne au modèle ce dont il a besoin dans une fenêtre limitée.', demo:'Budget de contexte', quiz:'Qu’est-ce qui consomme la fenêtre de contexte ?', minutes:9 },
{ id:'tome2-rag', tome:'Tome 2 · L’adaptation', number:9, title:'Donner tes documents au modèle, à la volée', eyebrow:'RAG', lead:'Le RAG ajoute des connaissances au moment de la réponse sans réentraîner le modèle.', demo:'Mini pipeline RAG', quiz:'En quoi le RAG diffère du fine-tuning ?', minutes:12 },
{ id:'tome2-finetuning', tome:'Tome 2 · L’adaptation', number:10, title:'Modifier les poids avec tes exemples', eyebrow:'Fine-tuning', lead:'Quand tu veux changer un comportement, un style ou un format, tu touches aux poids avec des exemples.', demo:'Avant / après spécialisation', quiz:'Quand choisir un fine-tuning ?', minutes:11 },
{ id:'tome2-rlhf', tome:'Tome 2 · L’adaptation', number:11, title:'De prédicteur de texte à assistant', eyebrow:'RLHF', lead:'Le RLHF transforme un modèle brut en assistant plus serviable, aligné et utile.', demo:'Feedback humain', quiz:'À quoi sert le modèle de récompense ?', minutes:10 },
{ id:'tome3-agent', tome:'Tome 3 · L’action', number:12, title:'Quand le modèle se met à agir', eyebrow:'Agent IA', lead:'Un agent place le modèle dans une boucle où il peut décider d’actions et observer leurs effets.', demo:'Chat vs agent', quiz:'Qu’est-ce qui distingue un agent ?', minutes:9 },
{ id:'tome3-tools', tome:'Tome 3 · L’action', number:13, title:'Le modèle ne fait rien… il demande qu’on le fasse', eyebrow:'Tool use', lead:'Le modèle choisit un outil, produit un appel structuré, puis lit le résultat.', demo:'Choix météo/calcul/web', quiz:'Que fait réellement un modèle qui utilise un outil ?', minutes:12 },
{ id:'tome3-loop', tome:'Tome 3 · L’action', number:14, title:'Réfléchir, agir, observer — recommencer', eyebrow:'Boucle agentique', lead:'Les tâches complexes demandent plusieurs tours : penser, agir, observer, ajuster.', demo:'Boucle ReAct', quiz:'Que décrit ReAct ?', minutes:11 },
{ id:'tome3-mcp', tome:'Tome 3 · L’action', number:15, title:'Le port universel entre l’IA et tes outils', eyebrow:'MCP', lead:'Le MCP standardise la connexion entre un agent et des serveurs d’outils.', demo:'Serveurs MCP branchés', quiz:'Dans MCP, que fait un serveur ?', minutes:10 },
{ id:'tome3-garde', tome:'Tome 3 · L’action', number:16, title:'Un agent qui agit doit être encadré', eyebrow:'Garde-fous', lead:'Plus l’agent agit, plus les erreurs coûtent cher. Les contenus externes restent des données, pas des ordres.', demo:'Prompt injection à repérer', quiz:'Que faire face à une instruction malveillante dans une page ?', minutes:10 },
] satisfies Module[] };
export const getModule = (id: string) => course.modules.find((module) => module.id === id);
